apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- django.yaml
- storageclass.yaml

secretGenerator:
- literals:
  - password=samplepassword123
  name: db-password
- literals:
  - secret=secretkey123
  name: django
